### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by balasankarc** [jgraichen/omniauth-multipassword#2]
Hi, I am packaging this gem for Debian as part of GitLab packaging. It would be a great help if you could add some tests that can be run to make sure the gem works fine. Thanks

**Comment by jgraichen** [comment]
I've added tests as well as coverage analysis. The codeclimate gem should be easy omitable.

Thanks for packaging. As a Debian user myself I have to thank you for your work. Feel free to ask if you need some more adjustments etc.

**Comment by balasankarc** [comment]
Cool. Thanks for the quick response. The following is the output I got while I ran the tests. Are they correct?


Randomized with seed 34199
I, [2015-05-18T20:11:12.442236 #8363]  INFO -- omniauth: (multipassword) Callback phase initiated.
E, [2015-05-18T20:11:12.457090 #8363] ERROR -- omniauth: (multipassword) Authentication failure! invalid_credentials encountered.
.I, [2015-05-18T20:11:12.462259 #8363]  INFO -- omniauth: (multipassword) Request phase initiated.
.I, [2015-05-18T20:11:12.465749 #8363]  INFO -- omniauth: (multipassword) Callback phase initiated.
.I, [2015-05-18T20:11:12.468127 #8363]  INFO -- omniauth: (multipassword) Callback phase initiated.
.....I, [2015-05-18T20:11:12.470806 #8363]  INFO -- omniauth: (onetest) Callback phase initiated.
E, [2015-05-18T20:11:12.471032 #8363] ERROR -- omniauth: (onetest) Authentication failure! invalid_credentials encountered.
.I, [2015-05-18T20:11:12.472084 #8363]  INFO -- omniauth: (onetest) Request phase initiated.
.I, [2015-05-18T20:11:12.474071 #8363]  INFO -- omniauth: (onetest) Callback phase initiated.
.

Finished in 0.11029 seconds (files took 0.97225 seconds to load)
11 examples, 0 failures

**Comment by jgraichen** [comment]
Yes. I get them too. Didn't had time to trace them down. Probably some default logger to `$stdout` in omniauth.

**Comment by balasankarc** [comment]
No, I meant, is it ok to see those "ERROR"s and messages like "Authentication failure!" etc?? Are they the outputs of a succesful test run?

PS : I am a noob in Ruby programming. Am actually learning it as I package. So, sorry if question is silly.

**Comment by balasankarc** [comment]
Cool.. BTW, can you tag the latest commit as a new version? So that I can use it for packaging.

**Comment by jgraichen** [comment]
I did right now including a release to RubyGems. (There is a single rake task for that.)

**Comment by balasankarc** [comment]
Thanks.. I'll package it and upload it to Debian. Hope it gets accepted soon. Thanks for your help.

**Comment by balasankarc** [comment]
I don't want to hijack this issue, but can similar tests be added to omniauth-kerberos and omniauth-internal also? If it is not much trouble?
