### ISSUE TITLE
Update omniauth dependency to 2.0

### ISSUE THREAD

**Issue by pravi** [jgraichen/omniauth-multipassword#3]
This gem is blocking update to omniauth 2.0

**Comment by jgraichen** [comment]
I just release `v2.0.0.rc1`, but as I currently do not use `omniauth-multipassword`, it would be awesome to check that this version works correctly for your app and OmniAuth 2.0 too.

**Comment by julienchabanon** [comment]
It does not work for me. See https://github.com/jgraichen/omniauth-kerberos/issues/5

**Comment by jgraichen** [comment]
All fixed in v2.0.1.
